### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Gibsol**
Fixed some grammar mistakes and the "latest" mistake in the first paragraph

### CODE REVIEW

**Comment by sunnamed434** [comment]
Good job. Could you please change the pull request target into the dev (i.e dev - patch-1)

**Comment by sunnamed434** [comment]
Alright, you did it a bit wrong that made it in the main branch, but it's okay, I'll fix it later then.

**Review by sunnamed434 — COMMENTED** [review]
Reviewed

**Comment by Gibsol** [comment]
It's actually a bit interesting what I have done here because I somehow forgot about the "latest" mistake. However I just fixed it.
Excuse me also for merging into the wrong branch. What should I do next then?

**Review by sunnamed434 — COMMENTED** [review]
All good, reviewed

**Comment by sunnamed434** [comment]
> It's actually a bit interesting what I have done here because I somehow forgot to fix the "latest" mistake. However I just fixed it. Excuse me also for merging into the wrong branch. What should I do next then?

Thanks for fixing it, I'll merge and fix the conflicts in the dev and main branches later.

**Pull request merged**
